detector/views.py
from flask import Blueprint
from flask import render_template, redirect, flash, url_for, send_from_directory
from flask import request, session
from .magic import RunTheDetectorDetector
from .models import ImageVariant, ImageRealestate, ImageAi, UniqueImage, DetectionResult, AIDetector
import matplotlib
matplotlib.use('Agg')  # Use the non-interactive backend suitable for scripts
import matplotlib.pylab as plt
from matplotlib.ticker import FuncFormatter
from sqlalchemy import or_, and_
from io import BytesIO
from flask import send_file
import seaborn as sns
import pandas as pd
import os
import re
import base64
from .seleniumScripts import ChatGPT

from .models import db

from PIL import Image, ImageStat

run_detector = RunTheDetectorDetector()


views = Blueprint('views', __name__)


""" Home Page """
@views.route('/')
def home():
    context = {}
    return render_template('index.html', context=context)



@views.route('/spesifikk')
def getspesificimage():
    imgs = ImageVariant.query.filter(ImageVariant.file_name == '20210913-_DSC3251.jpg', ImageVariant.edited == True).first()
    
    for result in imgs.detection_results:
        print(result.ai_result_float)
        print(result.detector.name)

    return "Ok"



@views.route('/matrix')
def matrix():
    imgs_unedited = ImageVariant.query.filter(ImageVariant.edited == False).all()
    imgs_ki = ImageAi.query.all()


    imgs = []
    i = 1
    for img in imgs_ki:
        imgs.append(img.getInfo(i))
        i += 1

    SORT_FOR = 'contentatscale.ai'

    df = pd.DataFrame(imgs)
    df_total_below_10 = df[(df[SORT_FOR] > 95)]
    df_total_above_50 = df_total_below_10[(df['isitAI.com'] < 50) | (df['illuminarty.ai'] < 50)]


    #melted_df = pd.melt(high_score_df, value_vars=['illuminarty.ai', 'contentatscale.ai'], var_name='Detector', value_name='Score')
    total_img = len(imgs_ki)
    print('Totalt:',  len(imgs_ki))
    print(len(df_total_below_10))
    print(len(df_total_above_50))

    labels = [f'Totalt antall bilder', 'ContentAtScale > 95%', 'Illuminarty eller IsItAI \n < 50%']
    counts = [len(imgs_ki), len(df_total_below_10), len(df_total_above_50)]


    # Creating a count plot
    fig, ax = plt.subplots(figsize=(10, 6))
    
    bars = ax.bar(labels, counts, color=['lightgray', 'lightgreen', 'lightblue', 'green'])
    ax.set_title(f'({SORT_FOR}) - Detektor variasjon for KI-bilder')
    ax.set_ylabel('Number of Images')

    # Adding text inside each bar
    for bar in bars:
        height = bar.get_height()
        ax.annotate(f'{height}',
                    xy=(bar.get_x() + bar.get_width() / 2, bar.get_y() + bar.get_height() / 2),
                    xytext=(0, 0),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='center', 
                    fontsize=16)

     # Save the plot to a BytesIO object instead of showing it
    img = BytesIO()
    plt.savefig(img, format='png')  # Correctly specify the format here
    img.seek(0)  # Go to the beginning of the BytesIO object"""

    # Return the plot as a response
    return send_file(img, mimetype='image/png')






@views.route('/movefiles')
def movefiles():
    def atoi(text):
        return int(text) if text.isdigit() else text
    # Function to split the filename into parts that are either digits or non-digits
    def natural_keys(text):
        return [atoi(c) for c in re.split(r'(\d+)', text)]


    LOAD_FROM = f'/Users/fure/03Prosjekter/VSProjects/AIDetectors/detector/static//Bildebank/temporary'
    LOAD_TO = f'/Users/fure/03Prosjekter/VSProjects/AIDetectors/detector/static//Bildebank/analyze'
    images = [os.path.join(LOAD_FROM, f) for f in sorted(os.listdir(LOAD_FROM), key=natural_keys) if f.endswith(('.jpg', '.jpeg', 'webp', 'png'))] 

    name = 442
    for img in images:
        file_type = img.split('.')[1]
        print(file_type)
        os.replace(img, f'{LOAD_TO}/{name}.{file_type}')
        name += 1


    return 'OK'


@views.route('/sammendrag')
def sammendrag():
    unedited_imgs = ImageVariant.query.filter(ImageVariant.edited == False).all()
    edited_imgs = ImageVariant.query.filter(ImageVariant.edited == True).all()
    re_imgs = ImageRealestate.query.filter_by().all()
    ki_imgs = ImageAi.query.all()

    mainUneditedList = []
    i = 1
    for img in unedited_imgs:
        mainUneditedList.append(img.getInfo(i))
        i += 1

    mainEditedList = []
    i = 1
    for img in edited_imgs:
        mainEditedList.append(img.getInfo(i))
        i += 1

    mainKIList = []
    i = 1
    for img in ki_imgs:
        mainKIList.append(img.getInfo(i))
        i += 1

    mainREList = []
    i = 1
    for img in re_imgs:
        mainREList.append(img.getInfo(i))
        i += 1
    
    unedited_data = pd.DataFrame(mainUneditedList)
    edited_data = pd.DataFrame(mainEditedList)
    ki_data = pd.DataFrame(mainKIList)
    re_data = pd.DataFrame(mainREList)

    # ALL COLUMS UNEDITED
    corr_data_unedtied = unedited_data.corr()
    corr_html_unedtied = corr_data_unedtied.to_html(classes='table table-striped')

    # DETECTORS ONLY UNEDITED
    detectors_only_unedited = unedited_data[['isitAI.com', 'illuminarty.ai', 'contentatscale.ai', 'hivemoderation.com']]
    detector_only_corr_unedited = detectors_only_unedited.corr()
    detector_only_corr_unedited_html = detector_only_corr_unedited.to_html(classes='table table-striped')

    # DETECTORS ONLY EDITED
    detectors_only_edited = edited_data[['isitAI.com', 'illuminarty.ai', 'contentatscale.ai', 'hivemoderation.com']]
    corr_data_edited = detectors_only_edited.corr()
    corr_html_edited = corr_data_edited.to_html(classes='table table-striped')

    # DETECTORS ONLY AI
    detectors_only_ai = ki_data[['isitAI.com', 'illuminarty.ai', 'contentatscale.ai', 'hivemoderation.com']]
    corr_data_ai = detectors_only_ai.corr()
    corr_html_ai = corr_data_ai.to_html(classes='table table-striped')

    # DETECTORS ONLY RE
    detectors_only_re = re_data[['isitAI.com', 'illuminarty.ai', 'contentatscale.ai', 'hivemoderation.com']]
    corr_data_re = detectors_only_re.corr()
    corr_html_re = corr_data_re.to_html(classes='table table-striped')

    

    def create_plot(data):
        plt.subplots(figsize=(7, 3))
        plt.xlabel('AI DETEKTOR')
        plt.ylabel('Sannsynlighet for KI (%)')
        plt.ylim(0, 100)

        print(len(data['isitAI.com']))

        sns.barplot(x=1, y=data['isitAI.com'], color='purple', label='1: isitAI.com',)
        sns.barplot(x=2, y=data['illuminarty.ai'], color='green', label='2: illuminarty.ai')
        sns.barplot(x=3, y=data['contentatscale.ai'], color='red', label='3: contentatscale.ai')
        sns.barplot(x=4, y=data['hivemoderation.com'], color='darkgray', label='4: hivemoderation.com')
        plt.legend()

        formatter = FuncFormatter(lambda x, _: f'{int(x)}%')
        plt.gca().yaxis.set_major_formatter(formatter)

        img = BytesIO()
        plt.savefig(img, format='png', bbox_inches='tight')
        img.seek(0)
        return img



    unedited_plot = create_plot(unedited_data)
    edited_plot = create_plot(edited_data)
    KI_plot = create_plot(ki_data)

    RE_plot = create_plot(re_data)

    context = {
        'isitAI.com': round(unedited_data['isitAI.com'].describe()[1], 2),
        'contentatscale.ai': round(unedited_data['contentatscale.ai'].describe()[1], 2),
        'illuminarty.ai': round(unedited_data['illuminarty.ai'].describe()[1], 2),
        'hivemoderation.com': round(unedited_data['hivemoderation.com'].describe()[1], 2),
        'KI_isitAI.com': round(ki_data['isitAI.com'].describe()[1], 2),
        'KI_contentatscale.ai': round(ki_data['contentatscale.ai'].describe()[1], 2),
        'KI_illuminarty.ai': round(ki_data['illuminarty.ai'].describe()[1], 2),
        'KI_hivemoderation.com': round(ki_data['hivemoderation.com'].describe()[1], 2),
        'RE_isitAI.com': round(re_data['isitAI.com'].describe()[1], 2),
        'RE_contentatscale.ai': round(re_data['contentatscale.ai'].describe()[1], 2),
        'RE_illuminarty.ai': round(re_data['illuminarty.ai'].describe()[1], 2),
        'RE_hivemoderation.com': round(re_data['hivemoderation.com'].describe()[1], 2),
        'edited_isitAI.com': round(edited_data['isitAI.com'].describe()[1], 2),
        'edited_contentatscale.ai': round(edited_data['contentatscale.ai'].describe()[1], 2),
        'edited_illuminarty.ai': round(edited_data['illuminarty.ai'].describe()[1], 2),
        'edited_hivemoderation.com': round(edited_data['hivemoderation.com'].describe()[1], 2),
        'unedited_plot': base64.b64encode(unedited_plot.getvalue()).decode('utf-8'),
        'edited_plot': base64.b64encode(edited_plot.getvalue()).decode('utf-8'),
        'KI_plot': base64.b64encode(KI_plot.getvalue()).decode('utf-8'),
        'RE_plot': base64.b64encode(RE_plot.getvalue()).decode('utf-8'),
        'total_real_imgs': len(unedited_data),
        'total_edited_imgs': len(edited_data),
        'total_KI_imgs': len(ki_data),
        'total_RE_imgs': len(re_data),
        'corr_html_unedited': corr_html_unedtied,
        'detectors_only_ai_corr': corr_html_ai,
        'detectors_only_unedited_corr': detector_only_corr_unedited_html,
        'detectors_only_edited_corr': corr_html_edited,
        'detectors_only_re_corr': corr_html_re,
        
    }

    return render_template('sammendrag.html', context=context)






""" RealEstate"""
@views.route('/realestate', methods=['GET', 'POST'])
def realestate():
    plt.subplots(figsize=(13, 7))
    imgs = ImageRealestate.query.filter(or_(ImageRealestate.exposure_sequence == 4, ImageRealestate.exposure_sequence == 5)).all()
    imgs = ImageRealestate.query.all()

    
    mainList = []
    i = 1
    for img in imgs:
        mainList.append(img.getInfo(i))
        i += 1

    pd_data = pd.DataFrame(mainList)

    SORT_BY = ['EXPOSURE']
    pd_data = pd_data.sort_values(by=SORT_BY)

    print(' ')
    print('BOLIGFOTO')

detector/templates/base.html
<!DOCTYPE html>
<html lang="no">
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/main.css') }}" async>
    </head>
    <body>
        {% block content %}

        {% endblock %}  
    </body>

</html>

detector/templates/documentation.html
{% extends "base.html" %}



{% block content %}

<style>

    main {
        display: flex;
        height: 100vh;
        width: 100vw;
        background-color: rgb(209, 209, 209);
    }

    .mainWrapper {
        margin: auto;
        display: flex;
        width: 800px;
        gap: 2rem;
        background-color: white;
        border-radius: .5rem;
        
    }

    article {
        padding: 1rem;
    }

</style>

<main>
    <div class="mainWrapper">
        <article>
            <h2>Documentation</h2><br>
            <p><strong>NAME:</strong> AI Detector Tester</p><br>
            <p>This app was built for the purpose of testing several AIDetectors, in connection with a bachelor thesis whether it's possible to disclose AI-images.</p><br>
            <p></p>
            <p>Currently the app can upload images to 4 detectors simultaneous: IsitAI.com, Illuminaty.ai, contentatscale.com and hivemoderation.com</p><br>
            
            <p>- The results are then saved in a SQL-database.</p>
            <p>- The upload procces of images are automated with Selenium. </p><br>

            <p>The app runs on a flask framework, making it very easy to view the saved results from different pages that can be configured to handle the data in different ways from a web browser locally.</p><br>

            <h3>Getting Started</h3>
            <p><strong>Installation:</strong> How to download and install the app.</p><br>
            Download the folder, then run the app from a codeeditor like VSCode or Pycharm after you have installed all the requaied python packages.</p><br>

            <h3>Troubleshooting</h3>
            <p>Kommer</p><br>

            <h3>Contact</h3>
            <p>thomasafure@gmail.com</p>
            
        </article>

    </div>
</main>


{% endblock %}

detector/templates/extremes.html
{% extends "base.html" %}


{% block content %}

<style>
    .filterWrapper {
        width: 100%;
        min-height: 200px;
    }

    .extremesWrapper .box1 {grid-area: box1; background-color: rgb(230, 230, 230);}   
    .extremesWrapper .box2 {grid-area: box2; background-color: rgb(230, 230, 230);} 
    .extremesWrapper {
        display: grid;
        grid-template-areas: 'box1 box2';
        grid-template-columns: 1fr 1fr;
        gap: 2rem;
        padding: 1rem;
    }

    .extremesWrapper .box1  h2,
    .extremesWrapper .box2  h2 {
        padding: 1rem;
    }

    .extremesWrapper .box1 .imgWrapper,
    .extremesWrapper .box2 .imgWrapper {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 1rem;
        padding: 1rem;
    }

    .extremesWrapper .box1 .imgWrapper img,
    .extremesWrapper .box2 .imgWrapper img {
        width: 100%;
    }


</style>
<div class="filterWrapper">
    <h2 style="padding: 1rem 3rem 0rem 3rem;">FILTER</h2>
    <form style="padding: 1rem 3rem;">
        <div style="display: flex; gap: .5rem;"><input type=checkbox><p>Utelukk boligfoto</p></div>
    </form>
</form>
</div>
<div class="extremesWrapper">
    <div class="box1">
        <h2>Under 1%</h2>
        <div class="imgWrapper">
            {% for img in context['img_low'] %}
            <img src="{{ url_for('static', filename=img.file_path) }}">
            {% endfor %}
        </div>
    </div>
    <div class="box2">
        <h2>Over 90%</h2>
        <div class="imgWrapper">
            {% for img in context['img_high'] %}
            <img src="{{ url_for('static', filename=img.file_path) }}">
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}  

detector/templates/index.html
{% extends "base.html" %}



{% block content %}
<style>

    main {
        display: flex;
        height: 100vh;
        background-color: rgb(209, 209, 209);
    }

    .mainWrapper {
        margin: auto;
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 2rem;
        
    }

    .box1, .box2 {
        margin: auto;
        padding: 2rem 3rem;
        background-color: rgb(255, 255, 255);
        width: 300px;
        height: 400px;
        border-radius: .5rem;
    }

    .box1 h3, .box2 h3 {
        margin-bottom: 2rem;
    }

</style>

<main>
    <div class="mainWrapper">
        <div class="box1">
            <h3>SAMMENDRAG</h3>
            <ul style="margin-left: 1rem;">
                <li><a href="{{ url_for('views.sammendrag') }}">Sammendrag</a></li>
                <li><a href="{{ url_for('views.html_graph') }}">HTML Graf</a></li>

            </ul>

        </div>
        <div class="box2">
            <h3>HANDLINGER</h3>
            <ul style="margin-left: 1rem;">
                <li><a href="{{ url_for('views.run') }}">Start</a></li>
                <li><a href="{{ url_for('views.movefiles') }}">Fjern metadata fra AI-bilder</a></li>
                <br>
                <br>
                <li><a href="{{ url_for('views.documentation') }}">Dokumentasjon</a></li>

            </ul>

        </div>
    </div>
</main>


{% endblock %}

detector/templates/run.html
{% extends "base.html" %}


{% block content %}
<style>
    .buttonWrapper {
        width: 100vw;
        height: 300px;
        display: flex;
    }
    .buttonWrapper form {
        margin: auto;
    }

    .buttonWrapper form button {
        background-color: rgb(51, 51, 51);
        color: white;
        padding: .5rem 2rem;
        font-weight: 600;
    }

</style>
<div class="buttonWrapper">
<form method="POST">
    <input hidden value="{{ csrf_token() }}" name="csrf_token" id="'csrf_token">
    <button>START DETEKTORER</button>
</form>
</div>
{% endblock %}

detector/templates/sammendrag.html
{% extends "base.html" %}


{% block content %}
<style>
    main {
        background-color: rgb(209, 209, 209);
        gap: 1rem;
        padding: 0 1rem;
    }

    .mainWrapper {
        display: grid;
        grid-template-columns: 1fr 1fr;
        height: fit-content;
        padding: 2rem;

    }

    .mainWrapper2 {
        display: flex;
        flex-direction: column;
        height: fit-content;
        padding: 0 0 5rem 0;

    }

    .box1, .box2 {
        margin: auto;
        padding: 2rem 2rem 1rem 2rem;
        background-color: white;
        border-radius: .5rem;
        box-shadow: 0 0 30px 0 rgba(84, 84, 84, 0.112);
        height: fit-content;
    }

    .bubble {
        background-color: rgb(239, 239, 239);
        padding: .2rem .8rem;
        border-radius: .3rem;
    }

    .corrWrapper {
        margin: 2rem auto auto auto;
        padding: 1rem;
        border-radius: .5rem;
        background-color: white;
    }

    .corrWrapper table td,
    .corrWrapper table th {
        padding: .2rem .3rem;
    }

    .corrWrapper h3 {
        padding: .5rem 1rem;
    }

    table {
    border-collapse: collapse; /* Collapses the border between table cells */
    width: 100%; /* Optional: Sets the width of the table */
    }

    table, th, td {
    border: 1px solid black; /* Sets the border around the table and cells */
    }

    th, td {
    padding: 8px; /* Adds some padding inside the cells */
    text-align: left; /* Aligns text to the left; can be adjusted as needed */
    }

    thead {
    background-color: #f2f2f2; /* Sets a background color for the table header */
    }

    tr:nth-child(even) {
    background-color: #ddd; /* Adds a background color to every even row */
    }

</style>

<main>
    <div class="mainWrapper">
        <div class="box1">
            <div style="margin-bottom: 1rem; margin-left: .5rem;">
                <p style="font-size: 18px;">Gjennomsnittlig sannsynlighet for KI basert på <strong>{{ context['total_real_imgs'] }}</strong> uredigerte bilder</p>
            </div>
            <div style="display: flex; gap: .5rem; width: fit-content; margin: 2rem auto .5rem auto;">
                <div class="bubble">
                    <h4>IsitAI</h4>
                    <p>{{ context['isitAI.com'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Illuminarty</h4>
                    <p>{{ context['illuminarty.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Contentatscale</h4>
                    <p>{{ context['contentatscale.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Hivemoderation</h4>
                    <p>{{ context['hivemoderation.com'] }}%</p>
                </div>
            </div>
            <div style="margin-top: 1rem">
                <img src="data:image/png;base64,{{ context['unedited_plot'] }}" alt="Barplot Image">
            </div>
        </div>
        <div class="box2">
            <div style="margin-bottom: 1rem; margin-left: .5rem;">
                <p style="font-size: 18px;">Gjennomsnittlig sannsynlighet for KI basert på <strong>{{ context['total_edited_imgs'] }}</strong> redigerte bilder</p>
            </div>
            <div style="display: flex; gap: .5rem; width: fit-content; margin: 2rem auto .5rem auto;">
                <div class="bubble">
                    <h4>IsitAI</h4>
                    <p>{{ context['edited_isitAI.com'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Illuminarty</h4>
                    <p>{{ context['edited_illuminarty.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Contentatscale</h4>
                    <p>{{ context['edited_contentatscale.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Hivemoderation</h4>
                    <p>{{ context['edited_hivemoderation.com'] }}%</p>
                </div>
            </div>
            <div style="margin-top: 1rem">
                <img src="data:image/png;base64,{{ context['edited_plot'] }}" alt="Barplot Image">
            </div>
        </div>
    </div>
    <div class="mainWrapper">
        <div class="box1">
            <div style="margin-bottom: 1rem; margin-left: .5rem;">
                <p style="font-size: 18px;">Gjennomsnittlig sannsynlighet for KI basert på <strong>{{ context['total_KI_imgs'] }}</strong> KI-genererte bilder</p>
            </div>
            <div style="display: flex; gap: .5rem; width: fit-content; margin: 2rem auto .5rem auto;">
                <div class="bubble">
                    <h4>IsitAI</h4>
                    <p>{{ context['KI_isitAI.com'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Illuminarty</h4>
                    <p>{{ context['KI_illuminarty.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Contentatscale</h4>
                    <p>{{ context['KI_contentatscale.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Hivemoderation</h4>
                    <p>{{ context['KI_hivemoderation.com'] }}%</p>
                </div>
            </div>
            <div style="margin-top: 1rem;">
                <img src="data:image/png;base64,{{ context['KI_plot'] }}" alt="Barplot Image">
            </div>
        </div>
        <div class="box2">
            <div style="margin-bottom: 1rem; margin-left: .5rem;">
                <p style="font-size: 18px;">Gjennomsnittlig sannsynlighet for KI basert på <strong>{{ context['total_RE_imgs'] }}</strong> uredigerte boligfoto</p>
            </div>
            <div style="display: flex; gap: .5rem; width: fit-content; margin: 2rem auto .5rem auto;">
                <div class="bubble">
                    <h4>IsitAI</h4>
                    <p>{{ context['RE_isitAI.com'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Illuminarty</h4>
                    <p>{{ context['RE_illuminarty.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Contentatscale</h4>
                    <p>{{ context['RE_contentatscale.ai'] }}%</p>
                </div>
                <div class="bubble">
                    <h4>Hivemoderation</h4>
                    <p>{{ context['RE_hivemoderation.com'] }}%</p>
                </div>
            </div>
            <div style="margin-top: 1rem;">
                <img src="data:image/png;base64,{{ context['RE_plot'] }}" alt="Barplot Image">
            </div>
        </div>
    </div>
    <div class="mainWrapper2">
        <div class="corrWrapper">
            <h3>Ekte uredigerte bilder</h3>
            {{ context['corr_html_unedited'] | safe }}
        </div>
        <div class="corrWrapper">
            <h3>Korrelasjon mellom detektorer for ekte uredigerte bilder</h3>
            {{ context['detectors_only_unedited_corr'] | safe }}
        </div>

        <div class="corrWrapper">
            <h3>Korrelasjon mellom detektorer for ekte redigerte bilder</h3>
            {{ context['detectors_only_edited_corr'] | safe }}
        </div>
        <div class="corrWrapper">
            <h3>Korrelasjon mellom detektorer for KI-bilder</h3>
            {{ context['detectors_only_ai_corr'] | safe }}
        </div>
        <div class="corrWrapper">
            <h3>Korrelasjon mellom detektorer for boligfoto</h3>
            {{ context['detectors_only_re_corr'] | safe }}
        </div>
    </div>
</main>
{% endblock %}

detector/templates/sorted_Fstop_index.html
{% extends "base.html" %}


{% block content %}
<style>
    .mainWrapper {
        height: 100vh;
        width: 100vw;
        padding: 5;
        background-color: lightcyan;
    }

    .graphWrapper {
        width: 100%;
        height: 100%;
        border-left: 2px solid gray;
        border-bottom: 2px solid gray;
    }
</style>

<div class="mainWrapper">
    <div class="graphWrapper flex">
        {% for data in context[]'data'] %}
        <div class="verticalLine">
            <div class="dotWrapper">
                <div class="dot">

                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}